# We are using Helm3 so we don't need according to the doc
installCRDs: false

# We don't want to complicate things too much regarding auth for this
# breakathon so we disable dex (https://github.com/dexidp/dex)
dex:
  enabled: false

server:
  #ingress:
  #  enabled: true
  #  annotations:
  #    kubernetes.io/tls-acme: "true"
  #    kubernetes.io/ingress.class: nginx
  #    nginx.ingress.kubernetes.io/force-ssl-redirect: true
  #    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  #    nginx.ingress.kubernetes.io/proxy-http-version: '1.0'
  #  hosts:
  #    - ${config.ingressHost}
  #  tls:
  #    - secretName: ${replace(config.ingressHost, ".", "-")}
  #      hosts:
  #        - ${config.ingressHost}
  #  https: true

  #ingressGrpc:
  #  enabled: true
  #  annotations:
  #    kubernetes.io/tls-acme: "true"
  #    kubernetes.io/ingress.class: nginx
  #    nginx.ingress.kubernetes.io/backend-protocol: GRPCS
  #  hosts:
  #    - ${format("grpc-%s", config.ingressHost)}
  #  tls:
  #    - secretName: ${format("grpc-%s", replace(config.ingressHost, ".", "-"))}
  #      hosts:
  #        - ${format("grpc-%s", config.ingressHost)}
  #  https: true

  config:
    #url: ${format("https://%s", config.ingressHost)}
    application.instanceLabelKey: app.kubernetes.io/instance

configs:
  secret:
    createSecret: true
