apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: digit-finder
  name: digit-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digit-finder
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: digit-finder
    spec:
      containers:
      - image: rg.nl-ams.scw.cloud/breakathon-xebia4ever/ai/digit-finder
        name: front
        env:
        - name: "REACT_APP_API_URL"
          value: "digit-finder-model"
      imagePullSecrets:
      - name: registry-secret

