apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZy5ubC1hbXMuc2N3LmNsb3VkIjp7InVzZXJuYW1lIjoibm9sb2dpbiIsInBhc3N3b3JkIjoiNTUzM2ExOTQtNjcxYi00OGU3LWFkNGYtYmQ5ZjM3ZmVjMmUzIiwiZW1haWwiOiJ4ZWJpYTRldmVyLWJyZWFrYXRob25AcHJvdG9ubWFpbC5jb20iLCJhdXRoIjoiYm05c2IyZHBiam8xTlRNellURTVOQzAyTnpGaUxUUTRaVGN0WVdRMFppMWlaRGxtTXpkbVpXTXlaVE09In19fQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-secret
type: kubernetes.io/dockerconfigjson
