apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  match:
    - excludedNamespaces: ["kube-system", "gatekeeper-system","k8s-addons", "kube-node-lease", "level1" ]
      processes: ["*"]
  sync:
    syncOnly:
      - group: "apps"
        version: "v1"
        kind: "Deployment"
      - group: "extensions"
        version: "v1beta1"
        kind: "Ingress"
      - group: "networking.k8s.io"
        version: "v1beta1"
        kind: "Ingress"
